@startuml
Читатель --> Книга: возврат
Читатель --> Книга: поиск
Читатель --> Книга: выбор
Библиотекарь --> Книга: выдача
Библиотекарь --> Книга: добавление
Библиотекарь --> Книга: списание

class Читатель {
  Фамилия
  Имя
  Отчество
  Номер телефона
  Адрес проживания
  Поиск книги()
  Выбор книги()
  Возврат книги()
}

class Книга {
  Номер книги
  Название
  Автор
  Жанр
}

class Библиотекарь {
  Паспортные данные
  Номер телефона
  Выдача книги()
  Добавление книги()
  Списание книги()
}
@enduml
