@startuml
left to right direction
skinparam packageStyle rectangle
actor Читатель
actor Библиотекарь
rectangle Библиотека {
  
  Читатель -- (Поиск книги)
  Читатель -- (Выбор книги)
  Читатель -- (Возврат книги)
  (Поиск по названию) .> (Поиск книги) : дополняет
  (Поиск по жанру) .> (Поиск книги) : дополняет
  (Поиск по автору) .> (Поиск книги) : дополняет
  (Выдача книги) -- Библиотекарь
  (Добавление книги) -- Библиотекарь
  (Списание книги) -- Библиотекарь
  (Поиск книги) .> (Просмотр списка\n доступных книг) : включает
  

}
@enduml
