@startuml 
left to right direction
database Библиотека
node Читатель
node Библиотекарь
node "Фильтры для поиска"

Читатель - Библиотека: Поиск книги/Возврат книги
Библиотекарь - Библиотека: Выдача книги/Добавление книги/Списание книги
Читатель - "Фильтры для поиска": Используют

@enduml
